/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CommandLine */

#ifndef _Included_CommandLine
#define _Included_CommandLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CommandLine
 * Method:    execCommand0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_CommandLine_execCommand0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
